services:
  api:
    build:
      context: ./src
      dockerfile: LoopMeet.Api/Dockerfile
    ports:
      - "8080:${API_PORT:-5001}"
    extra_hosts:
      - "dev.loopmeet.io:192.168.127.254"
    environment:  
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:${API_PORT:-5001}
      SUPABASE__URL: ${SUPABASE__URL:?Supabase URL is required}
      SUPABASE__ANONORPUBLISHABLEKEY: ${SUPABASE__ANONORPUBLISHABLEKEY:?Supabase Anon or Publishable Key is required}
      SUPABASE__SERVICEORSECRETKEY: ${SUPABASE__SERVICEORSECRETKEY:?Supabase Service or Secret Key is required}
      SUPABASE__JWTISSUER: ${SUPABASE__JWTISSUER:?Supabase JWT Issuer is required}
      SUPABASE__JWTAUDIENCE: ${SUPABASE__JWTAUDIENCE:-authenticated}
      SUPABASE__AVATARBUCKETNAME: ${SUPABASE__AVATARBUCKETNAME:-supabucket}
      GOOGLE__PLACESAPIKEY: ${GOOGLE__PLACESAPIKEY:?Google Places API Key is required}
    volumes:
      - ~/.microsoft/usersecrets/${API_ID:?Project ID is required}/secrets.json:/root/.microsoft/usersecrets/${API_ID}/secrets.json:ro
      - type: volume
        source: web-data
        target: /root/.aspnet/DataProtection-Keys
        volume:
          subpath: DataProtection-Keys

volumes:
  web-data:
